# slicer configs
zoom_level: 19
tile_size: 512
val_percent: 0.10

# train config
segm_arch: unet
arch: resnet50
optim: fused_adam
lr: 3e-4
workers: 8
wd: 1e-4
size: 256
bs: 32
decoder_warmup_epochs: 10
epochs: 100

name: test_run