## MODEL
segm_arch: unet
arch: se_resnet50

model_params:
  num_classes: 2
  drop_rate: 0.1

## OPTIMIZER
optim: adamw
wd: 1e-5


## CRITERION
criterion: [reduced_double_focal,  1]

## DATALOADER
augmentation: hard
bs: 16
dataset: ["dl_proj"]
size: 384
val_size: 512 # validate on whole images
workers: 8


## TRAINING
cutmix: True
opt_level: O1
# phases: [{"ep":[0, 2], "lr": [0, 0.5]}, {"ep":[2, 6], "lr": [0.5, 0.01]}, {"ep":[6, 50], "lr": [ 0.01 , 0], mode: "cos"}]
phases: [{"ep":[0, 50], "lr": [ 0.001 , 0], mode: "cos"}]

## RESUME & NAME
name: _dl_p.4.unet_ser50